### PR TITLE
Fix warnings in some precons

### PR DESCRIPTION
**Pull request by davidmartos96**
Indicate the exact printing in some of the precons to avoid the warnings

### CODE REVIEW

**Comment by taw** [comment]
Awesome, thanks. Hopefully they'll fix GN3 soon too.

**Comment by davidmartos96** [comment]
Yes, probably they are waiting for them to be added on Scryfall

**Comment by davidmartos96** [comment]
> Awesome, thanks. Hopefully they'll fix GN3 soon too.

@taw It seems that GN3 is now on MTGJSON :smile:

**Comment by taw** [comment]
GN3 done.

**Pull request merged**
