### PR TITLE
Change deck sets to QXX as necessary

### PR DESCRIPTION
**Pull request by axxroytovu**

### CODE REVIEW

**Comment by taw** [comment]
This won't import, I don't have any sets with zero cards, so these decks will be ignored.

`lib/sets.rb` is also automatically generated from db (which is generated from mtgjson data).

Supporting zero card sets would take some code restructuring. I'm not opposed to it, there just wasn't much point, as all they were good for were a tiny number of precons.

I can take a look at it if you think it would be helpful.

**Comment by axxroytovu** [comment]
Fair. I'm always going to be in favor of correctness over convenience but if it needs more effort than just my jury-rigged fix then I can wait. I'll put it in as an issue for later.

**Comment by taw** [comment]
This is probably fine now, but it would need to be verified.

**Comment by axxroytovu** [comment]
I'll double check it tomorrow and rebuild the pull request.

**Comment by axxroytovu** [comment]
Conflicts resolved, should be good to merge.

**Pull request merged**
