### PR TITLE
Raining Cats and Dogs Secret Lair Commander Deck

### PR DESCRIPTION
**Pull request by davidmartos96**
Work in progress on the recent Cats and Dogs Commander precon from Secret Lair.

Things to note:
* There are 3 alternative commanders
* There are 2 bonus cards that I placed in Sideboard
* ~~The Planeswalker icon stamped cards are left to annotated the specific collector number. I don't know if you have a way to automate that, since there was an update for those PLST cards recently in other decks.~~ DONE

### CODE REVIEW

**Comment by davidmartos96** [comment]
cc @axxroytovu Did you use any particular script for the PLST versions in the Secret Lair decks? Or was your change in the PLST pull request manual?

**Comment by axxroytovu** [comment]
Manual unfortunately. I don't know what collector numbers scryfall is going to use for cats & dogs yet.

**Comment by davidmartos96** [comment]
That's a bummer.
I'll see if I can update the PR tomorrow.

I looked a few of the cards and they seem to be available on Scryfall for the correct set, so they might have added them recently.

They are listed in the "Non-foil reprints" section with the set code https://magic.wizards.com/en/news/announcements/secret-lair-commander-deck-raining-cats-and-dogs

**Comment by taw** [comment]
I missed that it was marked as no longer draft for weeks now.

**Comment by taw** [comment]
> /Users/taw/github/magic-preconstructed-decks/data/cmd/sld/Raining Cats and Dogs.txt of type Commander Deck has unexpected section Sideboard

**Comment by davidmartos96** [comment]
@taw Yes, those are the bonus cards that came with the precon. I'm not sure if you have a better section for them.

**Comment by taw** [comment]
@axxroytovu Is this the only product with random cards added like that (not tokens or display commanders)? Did we ever decide what we're going to do with them?

**Comment by axxroytovu** [comment]
I think we should treat them like the other secret lair bonus cards. E.g. `// DISPLAY: Also includes one of: [SLD:683] Shadowborn Apostle, [SLD:650] Manaweft Sliver, or [SLD:654] Predatory Sliver.` from the OMG KITTEH secret lair

**Comment by axxroytovu** [comment]
Oh wait are they random or you get both cards? If you get both cards then I think the Sideboard makes sense. If it's random, then we should follow the precedent with the other secret lair products

**Comment by davidmartos96** [comment]
> Oh wait are they random or you get both cards? If you get both cards then I think the Sideboard makes sense. If it's random, then we should follow the precedent with the other secret lair products

For this bundle they are not random, everyone got those 2 extra cards.
Having an Extra/Bonus section could also be added, which is more general. Or use the sideboard

**Comment by taw** [comment]
I wanted to do bonus section, but IIRC every other non-randomized bonus card was a display commander or a token, so there were never any decks that needed it.

I guess it can be a Sideboard for now.

**Pull request merged**
