### PR TITLE
Commander Masters decks

### PR DESCRIPTION
**Pull request by davidmartos96**

### CODE REVIEW

**Comment by taw** [comment]
There are two cards the indexer can't resolve:

```
bin/resolve_card "cmm" "Enduring Enchantments" "Demon of Fate's Design" "[CMM:731]"
bin/resolve_card "cmm" "Enduring Enchantments" "Demon of Fate's Design" "[CMM:762]"
bin/resolve_card "cmm" "Enduring Enchantments" "Nyxborn Behemoth" "[CMM:742]"
bin/resolve_card "cmm" "Enduring Enchantments" "Nyxborn Behemoth" "[CMM:772]"
```

**Comment by davidmartos96** [comment]
Doesn't it pick the non extended art version automatically?

**Comment by taw** [comment]
It normally does if metadata is complete. 

Right now data says it's "Frame Effects: nyxtouched" vs "Frame Effects: extendedart" and it doesn't know how to prioritize between them, so it needs explicit annotations.

(arguably extendedart version has some nyxtouched parts, so it probably should have both, and then the indexer would know what to do)

**Comment by taw** [comment]
I tagged the non-extendedart ones.

**Pull request merged**
