### PR TITLE
Angels SLD Commander deck

### PR DESCRIPTION
**Pull request by davidmartos96**
This is the recently released Secret Lair Commander deck.
Same as the From Cute to Brute SLD deck, most cards have the planeswalker symbol stamped in the corner (like The List cards), but these are not yet available on Scryfall/MTGJSON.
I'm not sure if there would be a way for the resolver to correctly index the deck, I wasn't able to.

Additionally there is not a particular set code here (at least yet) so I chose "sld"

Decklist
https://magic.wizards.com/en/news/announcements/secret-lairs-next-commander-deck-takes-flight

### CODE REVIEW

**Comment by taw** [comment]
Should we wait until mtgjson adds the cards then?

**Comment by davidmartos96** [comment]
@taw Would it be possible to index the deck anyway but the non SLD cards are taken from any "regular" set? And when those cards are actually present in the database, reindex the deck with the correct printings.
I'm not sure if there is an easy config in the source code to do that kind of thing.

**Comment by taw** [comment]
It could be done, but it's more work, so let's just wait for mtgjson.

**Comment by davidmartos96** [comment]
The Angels "set" is now available in both MTGJSON and Scryfall 

https://scryfall.com/sets/pagl?as=grid&order=set


Side note: 
When indexing with latest cards, "The Walking Dead foil" txt file was having issues due to recent renaming on aliased cards from Universes Within.
I'm not sure if you have additional code to handle that, but this is what I changed to save you some time if you take the rename route :sweat_smile: 
```
// NAME: The Walking Dead - Foil
// SOURCE: https://mtg.fandom.com/wiki/Secret_Lair_Drop_Series:_The_Walking_Dead
// DATE: 2020-10-13
1 [SLD:143] Greymond, Avacyn's Stalwart [foil]
1 [SLD:144] Hansk, Slayer Zealot [foil]
1 [SLD:145] Gregor, Shrewd Magistrate [foil]
1 [SLD:146] Enkira, Hostile Scavenger [foil]
1 [SLD:147] Malik, Grim Manipulator [foil]
1 [SLD:148] Walker [foil] [token]
1 [SLD:149] Walker [foil] [token]
1 [SLD:150] Walker [foil] [token]
1 [SLD:151] Walker [foil] [token]
1 [SLD:152] Walker [foil] [token]
1 [SLD:153] Treasure [foil] [token]

Sideboard
1 [SLD:581] Gisa's Favorite Shovel [foil]
```

**Comment by taw** [comment]
SLD is currently broken on mtgjson, so I'm not updating it until https://github.com/mtgjson/mtgjson/issues/1110 is fixed

**Comment by taw** [comment]
I merged it. [Is this correct](https://mtg.wtf/deck/pagl/angels-they-re-just-like-us-but-cooler-and-with-wings)?

Especially foiling decisions look completely random.

**Comment by davidmartos96** [comment]
Yes, it is correct. It looks random because the release notes were incomplete. There were more foils than the ones listed in the announcement.
I double checked with a video opening the deck.
But if you see the available finishes for those additional foils you will also see that they are only available in foil on Scryfall, TCGplayer and MTGJSON.

**Comment by taw** [comment]
OK, I'll just leave the foiling information like it is. Hopefully it's all accurate.

**Pull request merged**
