### PR TITLE
Fix two more collector numbers in 20 Ways to Win deck

### PR DESCRIPTION
**Pull request by kodawah**

### CODE REVIEW

**Comment by taw** [comment]
I'll just check it locally without merging so we don't do 20 PRs:

There's no Estrid's Invocation in SLD at least right now.

Metadata block has errors (extra brackets and wrong name):

```
// NAME: Raining Cats and Dogs]
// SOURCE: https://magic.wizards.com/en/news/announcements/secret-lair-commander-deck-20-ways-to-win-full-decklist]
// DATE: 2024-12-04]
```

Warnings:

```
/Users/taw/github/magic-preconstructed-decks/data/cmd/sld/20 Ways to Win.txt of type Commander Deck section Main Deck has invalid size 101, should be [98, 99]
/Users/taw/github/magic-preconstructed-decks/data/cmd/sld/20 Ways to Win.txt of type Commander Deck section Main Deck + Commander has invalid size 102, should be 100
```

First errors of each deck:

```
Skipping deck Secret Lair Drop - 20 Ways to Win due to error: Number ??? requested for Soul's Attendant but no such card found. Available numbers: ROE-44
Skipping deck Secret Lair Drop - The Fairest Drop of All foil due to error: Set sld explicitly specified but no such printing for Estrid's Invocation
```

**Comment by taw** [comment]
```
Skipping deck Secret Lair Drop - The Fairest Drop of All foil due to errors:
* Set sld explicitly specified but no such printing for Estrid's Invocation
* Set sld explicitly specified but no such printing for Steely Resolve
* Set sld explicitly specified but no such printing for Estrid, the Masked
* Card not found sld Tuvasa, the Sunlit
```

**Comment by kodawah** [comment]
> ```
> Skipping deck Secret Lair Drop - The Fairest Drop of All foil due to errors:
> * Set sld explicitly specified but no such printing for Estrid's Invocation
> * Set sld explicitly specified but no such printing for Steely Resolve
> * Set sld explicitly specified but no such printing for Estrid, the Masked
> * Card not found sld Tuvasa, the Sunlit
> ```

i assume scryfall doesn't have those yet

**Comment by taw** [comment]
I'll merge the fixes we have now, we can fix the other deck later.

**Pull request merged**
