### PR TITLE
Added Standard Challenger Decks 2022

### PR DESCRIPTION
**Pull request by SuppenNudel**
Those Decks were released on 1st April 2022

### CODE REVIEW

**Comment by taw** [comment]
Thanks. I added them to NEO as mtgjson doesn't have Q07.

**Comment by taw** [comment]
By the way if you just give me url and date, I have scripts to do everything else.

**Comment by SuppenNudel** [comment]
Got to know and makes sense.
Why does the Pioneer Challenger Decks have q06 as a code, but the standard ones don't start with q? Looking at MTG wiki - and I trust them at that - the challenger decks all have a code qxx

**Comment by taw** [comment]
There are a few cards in them that have Q06 printed on the card (majority have set code).

I don't think any physical card have Q07 printed on them, it's always set code.

The reason why Pioneer decks need extra cards is because they don't want to include old frame cards or such cases in the same product.

**Comment by SuppenNudel** [comment]
Can you tell me, when mtg.wtf or mtgjson will be updated with this new data?

**Comment by taw** [comment]
All new decks are on https://mtg.wtf/deck
mtgjson picks up the data every time they do update

**Pull request closed without merging**
