### PR TITLE
Starter Commander decks

### PR DESCRIPTION
**Pull request by davidmartos96**
Decks from https://magic.wizards.com/en/news/announcements/starter-commander-decks-decklists-2022-10-20

### CODE REVIEW

**Comment by davidmartos96** [comment]
I believe the `url2txt` script needs to be updated since the way the decks are displayed in magic.wizards.com has changed

**Comment by taw** [comment]
OK, I'll take a look at url2txt

**Comment by taw** [comment]
I see the website currently doesn't mark commanders in any way, so they'd need to be added manually, but that's also true for foiling, for release date etc.

**Comment by davidmartos96** [comment]
That's unfortunate. Then aside the cards only the deck name can be extracted.

**Comment by taw** [comment]
OK, url2txt updated. Commanders are mentioned on the page just before the decklist (first `figure-wrapper > figure > img`), so in principle this could be doable, but for now I didn't bother with commander extraction.

**Pull request merged**
