### PR TITLE
Foundations Starter Collection fixes

### PR DESCRIPTION
**Pull request by davidmartos96**
WIP for the Foundation Starter Collection sealed contents.
It's a WIP because MTGJSON is currently having issues so last data is from the 28th, which doesn't include some of the cards in the box.

I added the box as separate entries (by color), as they do in the announcement site, otherwise it would be a single entry with over 350 cards, which I'm not sure you are comfortable with.

### CODE REVIEW

**Comment by taw** [comment]
They aren't separate decks, and all come in one box right? So it probably should be a single 350 card product.

**Comment by taw** [comment]
[I got another PR for Foundation](https://github.com/taw/magic-preconstructed-decks/pull/144/files#diff-f458a32f9112d8994368098849a5dc1305c7d00d00b6127829b6d8f6f06c5fc8). Can you or @axxroytovu check that it all matches?

**Comment by axxroytovu** [comment]
Looks like this PR is more correct than mine. I didn't bother parsing out the full art lands and I think the 15th is the official release date.

**Comment by davidmartos96** [comment]
@taw I resolved the merge conflicts. Now it's basically the date corrected + the basic lands
I saw the date in the Amazon product page as well as other online stores
https://www.amazon.com/Magic-Gathering-Foundations-Starter-Collection/dp/B0D9KYHN4D

**Pull request merged**
