### PR TITLE
Some sld decks

### PR DESCRIPTION
**Pull request by kodawah**

### CODE REVIEW

**Comment by taw** [comment]
I'm not sure if we support  "1 [SLU:11] Barkchannel Pathway // Tidechannel Pathway [foil]" notation. Well best way to find out is to merge.

**Comment by kodawah** [comment]
yolo!

**Comment by taw** [comment]
OK, so it works, but gives me warnings:

```
Number 11 requested for Barkchannel Pathway, no such card found, but works when corrected to 11a
Number 12 requested for Blightstep Pathway, no such card found, but works when corrected to 12a
Number 13 requested for Branchloft Pathway, no such card found, but works when corrected to 13a
Number 14 requested for Brightclimb Pathway, no such card found, but works when corrected to 14a
Number 15 requested for Clearwater Pathway, no such card found, but works when corrected to 15a
Number 16 requested for Cragcrown Pathway, no such card found, but works when corrected to 16a
Number 17 requested for Darkbore Pathway, no such card found, but works when corrected to 17a
Number 18 requested for Hengegate Pathway, no such card found, but works when corrected to 18a
Number 19 requested for Needleverge Pathway, no such card found, but works when corrected to 19a
Number 20 requested for Riverglide Pathway, no such card found, but works when corrected to 20a
```

I'm not sure if this warning is really needed, it's clear enough either way.

**Comment by kodawah** [comment]
oh i guess it's because it's a dual faced card the SF collector number adds an extra "a" to the front (and a "b") to the back

**Pull request merged**
