### PR TITLE
Add Commander Anthology Volume II

### PR DESCRIPTION
**Pull request by fenhl**
This adds the decklists for CM2, including foil information sourced from [this unboxing video](https://www.youtube.com/watch?v=n3QjGzXWsd4).

I've also added `decks.json` to the gitignore, since it's generated by the validation but not in the repo.

### CODE REVIEW

**Comment by fenhl** [comment]
I'm not sure why it's not on Gatherer yet. MTG JSON should hopefully have it as well at some point, since the goal is to have all printings of all cards.

**Comment by taw** [comment]
I'll merge this PR once CM2 is in the db (unless it takes forever and we need to add it manually).

**Comment by fenhl** [comment]
I guess we'll have to see whether Gatherer updates on Wednesday.

**Comment by taw** [comment]
mtgjson doesn't seem interested, so I imported CM2 from gatherer and manually fixed that one flip card

**Comment by taw** [comment]
My validation script doesn't like these foiling choices, need to verify.

**Comment by taw** [comment]
Well, it seems it's all right. It's the first time ever different decks have different number of foils in them.

[Wizards](https://magic.wizards.com/en/articles/archive/news/commander-anthology-vol-ii-legends-and-decklists-2018-05-08) lists 12/13 foils, somehow skips Daretti, but that's confirmed foil by everyone.

**Pull request merged**
