### PR TITLE
Add all the Salvat decks

### PR DESCRIPTION
**Pull request by axxroytovu**

### CODE REVIEW

**Comment by taw** [comment]
I specifically exclude foreign printings from db unless they're unique, so I excluded all Salvat stuff and similar: FBB, 4BB, REN, RIN, PSAL, PS11, BCHR.

Should I change this?

**Comment by axxroytovu** [comment]
I can try and associate them with a non-foreign set.

**Comment by taw** [comment]
Oh yeah, that would be the easiest.

I can change treatment of these sets if we have to, but if they can just be reassigned, that's easier.

**Comment by axxroytovu** [comment]
So it's theoretically possible to associate these with foreign sets, but it's a LOT of work and I'm still parsing through them. I basically need to find the last black border printing for each card individually since most of them are too old for the indexer to like.

**Comment by taw** [comment]
Is it always the most recent standard-legal printing?

**Comment by axxroytovu** [comment]
I mean, many of the cards have a completely different frame from their prior printing. All of the Salvat 2005 cards are in the 8ed frame, where many of them were only ever old border. 

The problem is that the same deck can have cards from M11 (2010) and Odyssey (2001) and every set in between.

**Comment by taw** [comment]
OK, I don't think these can be reassigned to any other set, so I added Salvat, and fixed a few typos in these.

Unfortunately there's a lot of unresolved printings:

```
bin/resolve_card "psal" "Angels" "Angel of Mercy" "[PSAL:G14]"
bin/resolve_card "psal" "Angels" "Angel of Mercy" "[PSAL:G38]"
bin/resolve_card "psal" "Angels" "Ardent Militia" "[PSAL:G15]"
bin/resolve_card "psal" "Angels" "Ardent Militia" "[PSAL:G26]"
bin/resolve_card "psal" "Angels" "Auratouched Mage" "[PSAL:G27]"
bin/resolve_card "psal" "Angels" "Auratouched Mage" "[PSAL:G50]"
bin/resolve_card "psal" "Angels" "Freewind Equenaut" "[PSAL:G17]"
bin/resolve_card "psal" "Angels" "Freewind Equenaut" "[PSAL:G4]"
bin/resolve_card "psal" "Angels" "Freewind Equenaut" "[PSAL:G41]"
bin/resolve_card "psal" "Angels" "Nightguard Patrol" "[PSAL:G18]"
bin/resolve_card "psal" "Angels" "Nightguard Patrol" "[PSAL:G29]"
bin/resolve_card "psal" "Angels" "Skyrider Trainee" "[PSAL:G54]"
bin/resolve_card "psal" "Angels" "Skyrider Trainee" "[PSAL:G6]"
bin/resolve_card "psal" "Angels" "Soulsworn Jury" "[PSAL:G43]"
bin/resolve_card "psal" "Angels" "Soulsworn Jury" "[PSAL:G44]"
bin/resolve_card "psal" "Angels" "Guardian's Magemark" "[PSAL:G5]"
bin/resolve_card "psal" "Angels" "Guardian's Magemark" "[PSAL:G52]"
bin/resolve_card "psal" "Angels" "Infiltrator's Magemark" "[PSAL:G19]"
bin/resolve_card "psal" "Angels" "Infiltrator's Magemark" "[PSAL:G7]"
bin/resolve_card "psal" "Angels" "Pacifism" "[PSAL:G42]"
bin/resolve_card "psal" "Angels" "Pacifism" "[PSAL:G53]"
bin/resolve_card "psal" "Angels" "Plumes of Peace" "[PSAL:G31]"
bin/resolve_card "psal" "Angels" "Plumes of Peace" "[PSAL:G55]"
bin/resolve_card "psal" "Angels" "Spirit Link" "[PSAL:C40]"
bin/resolve_card "psal" "Angels" "Spirit Link" "[PSAL:G3]"
bin/resolve_card "psal" "Beasts" "Enormous Baloth" "[PSAL:K2]"
bin/resolve_card "psal" "Beasts" "Enormous Baloth" "[PSAL:K50]"
bin/resolve_card "psal" "Beasts" "Fangren Pathcutter" "[PSAL:K14]"
bin/resolve_card "psal" "Beasts" "Fangren Pathcutter" "[PSAL:K15]"
bin/resolve_card "psal" "Beasts" "Flowstone Shambler" "[PSAL:K53]"
bin/resolve_card "psal" "Beasts" "Flowstone Shambler" "[PSAL:K7]"
bin/resolve_card "psal" "Beasts" "Groffskithur" "[PSAL:K30]"
bin/resolve_card "psal" "Beasts" "Groffskithur" "[PSAL:K41]"
bin/resolve_card "psal" "Beasts" "Groffskithur" "[PSAL:K42]"
bin/resolve_card "psal" "Beasts" "Groffskithur" "[PSAL:K55]"
bin/resolve_card "psal" "Beasts" "Indrik Stomphowler" "[PSAL:I38]"
bin/resolve_card "psal" "Beasts" "Indrik Stomphowler" "[PSAL:K38]"
bin/resolve_card "psal" "Beasts" "Indrik Stomphowler" "[PSAL:K51]"
bin/resolve_card "psal" "Beasts" "Iron-Barb Hellion" "[PSAL:K3]"
bin/resolve_card "psal" "Beasts" "Iron-Barb Hellion" "[PSAL:K4]"
bin/resolve_card "psal" "Beasts" "Rampant Growth" "[PSAL:K19]"
bin/resolve_card "psal" "Beasts" "Rampant Growth" "[PSAL:K28]"
bin/resolve_card "psal" "Beasts" "Volcanic Hammer" "[PSAL:C43]"
bin/resolve_card "psal" "Beasts" "Volcanic Hammer" "[PSAL:K17]"
bin/resolve_card "psal" "Beasts" "Volcanic Hammer" "[PSAL:K31]"
bin/resolve_card "psal" "Beasts" "Fertile Ground" "[PSAL:K5]"
bin/resolve_card "psal" "Beasts" "Fertile Ground" "[PSAL:K6]"
bin/resolve_card "psal" "Beasts" "Lure" "[PSAL:K16]"
bin/resolve_card "psal" "Beasts" "Lure" "[PSAL:K39]"
bin/resolve_card "psal" "Berserk" "Ghor-Clan Savage" "[PSAL:I29]"
bin/resolve_card "psal" "Berserk" "Ghor-Clan Savage" "[PSAL:I55]"
bin/resolve_card "psal" "Berserk" "Goblin Chariot" "[PSAL:I17]"
bin/resolve_card "psal" "Berserk" "Goblin Chariot" "[PSAL:I18]"
bin/resolve_card "psal" "Berserk" "Goblin Chariot" "[PSAL:I4]"
bin/resolve_card "psal" "Berserk" "Gruul Scrapper" "[PSAL:I42]"
bin/resolve_card "psal" "Berserk" "Gruul Scrapper" "[PSAL:I43]"
bin/resolve_card "psal" "Berserk" "Indrik Stomphowler" "[PSAL:I38]"
bin/resolve_card "psal" "Berserk" "Indrik Stomphowler" "[PSAL:K38]"
bin/resolve_card "psal" "Berserk" "Indrik Stomphowler" "[PSAL:K51]"
bin/resolve_card "psal" "Berserk" "Primal Forcemage" "[PSAL:I39]"
bin/resolve_card "psal" "Berserk" "Primal Forcemage" "[PSAL:I40]"
bin/resolve_card "psal" "Berserk" "Primal Forcemage" "[PSAL:I52]"
bin/resolve_card "psal" "Berserk" "Raging Goblin" "[PSAL:I41]"
bin/resolve_card "psal" "Berserk" "Raging Goblin" "[PSAL:I6]"
bin/resolve_card "psal" "Berserk" "Raging Goblin" "[PSAL:I7]"
bin/resolve_card "psal" "Berserk" "Scab-Clan Mauler" "[PSAL:I31]"
bin/resolve_card "psal" "Berserk" "Scab-Clan Mauler" "[PSAL:I56]"
bin/resolve_card "psal" "Berserk" "Balduvian Rage" "[PSAL:I14]"
bin/resolve_card "psal" "Berserk" "Balduvian Rage" "[PSAL:I15]"
bin/resolve_card "psal" "Berserk" "Shock" "[PSAL:I53]"
bin/resolve_card "psal" "Berserk" "Shock" "[PSAL:I54]"
bin/resolve_card "psal" "Berserk" "Feral Lightning" "[PSAL:I2]"
bin/resolve_card "psal" "Berserk" "Feral Lightning" "[PSAL:I50]"
bin/resolve_card "psal" "Berserk" "Threaten" "[PSAL:I26]"
bin/resolve_card "psal" "Berserk" "Threaten" "[PSAL:I27]"
bin/resolve_card "psal" "Cats" "Terramorphic Expanse" "[PSAL:L20]"
bin/resolve_card "psal" "Cats" "Terramorphic Expanse" "[PSAL:L34]"
bin/resolve_card "psal" "Cats" "Terramorphic Expanse" "[PSAL:L45]"
bin/resolve_card "psal" "Cats" "Terramorphic Expanse" "[PSAL:L8]"
bin/resolve_card "psal" "Cats" "Selesnya Sanctuary" "[PSAL:L33]"
bin/resolve_card "psal" "Cats" "Selesnya Sanctuary" "[PSAL:L44]"
bin/resolve_card "psal" "Cats" "Skyhunter Skirmisher" "[PSAL:L3]"
bin/resolve_card "psal" "Cats" "Skyhunter Skirmisher" "[PSAL:L39]"
bin/resolve_card "psal" "Cats" "Skyhunter Cub" "[PSAL:L18]"
bin/resolve_card "psal" "Cats" "Skyhunter Cub" "[PSAL:L42]"
bin/resolve_card "psal" "Cats" "Skyhunter Cub" "[PSAL:L7]"
bin/resolve_card "psal" "Cats" "Arctic Nishoba" "[PSAL:L14]"
bin/resolve_card "psal" "Cats" "Arctic Nishoba" "[PSAL:L26]"
bin/resolve_card "psal" "Cats" "Leonin Den-Guard" "[PSAL:L17]"
bin/resolve_card "psal" "Cats" "Leonin Den-Guard" "[PSAL:L29]"
bin/resolve_card "psal" "Cats" "Leonin Den-Guard" "[PSAL:L30]"
bin/resolve_card "psal" "Cats" "Skyhunter Patrol" "[PSAL:L19]"
bin/resolve_card "psal" "Cats" "Skyhunter Patrol" "[PSAL:L54]"
bin/resolve_card "psal" "Cats" "Saltblast" "[PSAL:L28]"
bin/resolve_card "psal" "Cats" "Saltblast" "[PSAL:L53]"
bin/resolve_card "psal" "Cats" "Bonesplitter" "[PSAL:L40]"
bin/resolve_card "psal" "Cats" "Bonesplitter" "[PSAL:L5]"
bin/resolve_card "psal" "Cats" "Grifter's Blade" "[PSAL:L27]"
bin/resolve_card "psal" "Cats" "Grifter's Blade" "[PSAL:L50]"
bin/resolve_card "psal" "Cats" "Selesnya Signet" "[PSAL:L41]"
bin/resolve_card "psal" "Cats" "Selesnya Signet" "[PSAL:L55]"
bin/resolve_card "psal" "Cats" "Selesnya Signet" "[PSAL:L56]"
bin/resolve_card "psal" "Elves" "Nullmage Shepherd" "[PSAL:B2]"
bin/resolve_card "psal" "Elves" "Nullmage Shepherd" "[PSAL:B40]"
bin/resolve_card "psal" "Elves" "Wirewood Hivemaster" "[PSAL:B3]"
bin/resolve_card "psal" "Elves" "Wirewood Hivemaster" "[PSAL:B4]"
bin/resolve_card "psal" "Elves" "Treetop Scout" "[PSAL:B5]"
bin/resolve_card "psal" "Elves" "Treetop Scout" "[PSAL:B6]"
bin/resolve_card "psal" "Elves" "Sylvan Messenger" "[PSAL:B14]"
bin/resolve_card "psal" "Elves" "Sylvan Messenger" "[PSAL:B15]"
bin/resolve_card "psal" "Elves" "Llanowar Elite" "[PSAL:B16]"
bin/resolve_card "psal" "Elves" "Llanowar Elite" "[PSAL:B17]"
bin/resolve_card "psal" "Elves" "Timberwatch Elf" "[PSAL:B18]"
bin/resolve_card "psal" "Elves" "Timberwatch Elf" "[PSAL:B19]"
bin/resolve_card "psal" "Elves" "Seeker of Skybreak" "[PSAL:B29]"
bin/resolve_card "psal" "Elves" "Seeker of Skybreak" "[PSAL:B30]"
bin/resolve_card "psal" "Elves" "Elvish Warrior" "[PSAL:B41]"
bin/resolve_card "psal" "Elves" "Elvish Warrior" "[PSAL:B42]"
bin/resolve_card "psal" "Elves" "Golgari Guildmage" "[PSAL:B50]"
bin/resolve_card "psal" "Elves" "Golgari Guildmage" "[PSAL:F39]"
bin/resolve_card "psal" "Elves" "Selesnya Guildmage" "[PSAL:B51]"
bin/resolve_card "psal" "Elves" "Selesnya Guildmage" "[PSAL:J51]"
bin/resolve_card "psal" "Elves" "Birchlore Rangers" "[PSAL:B52]"
bin/resolve_card "psal" "Elves" "Birchlore Rangers" "[PSAL:B53]"
bin/resolve_card "psal" "Elves" "Wirewood Pride" "[PSAL:B32]"
bin/resolve_card "psal" "Elves" "Wirewood Pride" "[PSAL:B44]"
bin/resolve_card "psal" "Elves" "Wirewood Pride" "[PSAL:B55]"
bin/resolve_card "psal" "Elves" "Crown of Vigor" "[PSAL:B54]"
bin/resolve_card "psal" "Elves" "Crown of Vigor" "[PSAL:D6]"
bin/resolve_card "psal" "Ninjas" "Dimir Infiltrator" "[PSAL:E4]"
bin/resolve_card "psal" "Ninjas" "Dimir Infiltrator" "[PSAL:E5]"
bin/resolve_card "psal" "Ninjas" "Merfolk of the Pearl Trident" "[PSAL:E42]"
bin/resolve_card "psal" "Ninjas" "Merfolk of the Pearl Trident" "[PSAL:E43]"
bin/resolve_card "psal" "Ninjas" "Ninja of the Deep Hours" "[PSAL:E30]"
bin/resolve_card "psal" "Ninjas" "Ninja of the Deep Hours" "[PSAL:E41]"
bin/resolve_card "psal" "Ninjas" "Ninja of the Deep Hours" "[PSAL:E6]"
bin/resolve_card "psal" "Ninjas" "Okiba-Gang Shinobi" "[PSAL:E53]"
bin/resolve_card "psal" "Ninjas" "Okiba-Gang Shinobi" "[PSAL:E54]"
bin/resolve_card "psal" "Ninjas" "Sage Owl" "[PSAL:E31]"
bin/resolve_card "psal" "Ninjas" "Sage Owl" "[PSAL:E7]"
bin/resolve_card "psal" "Ninjas" "Skullsnatcher" "[PSAL:A4]"
bin/resolve_card "psal" "Ninjas" "Skullsnatcher" "[PSAL:A42]"
bin/resolve_card "psal" "Ninjas" "Skullsnatcher" "[PSAL:A43]"
bin/resolve_card "psal" "Ninjas" "Skullsnatcher" "[PSAL:E17]"
bin/resolve_card "psal" "Ninjas" "Skullsnatcher" "[PSAL:E18]"
bin/resolve_card "psal" "Ninjas" "Skullsnatcher" "[PSAL:E19]"
bin/resolve_card "psal" "Ninjas" "Throat Slitter" "[PSAL:E2]"
bin/resolve_card "psal" "Ninjas" "Throat Slitter" "[PSAL:E3]"
bin/resolve_card "psal" "Ninjas" "Walker of Secret Ways" "[PSAL:E51]"
bin/resolve_card "psal" "Ninjas" "Walker of Secret Ways" "[PSAL:E52]"
bin/resolve_card "psal" "Ninjas" "Clutch of the Undercity" "[PSAL:E14]"
bin/resolve_card "psal" "Ninjas" "Clutch of the Undercity" "[PSAL:E38]"
bin/resolve_card "psal" "Ravenous Rats" "Swarm of Rats" "[PSAL:A14]"
bin/resolve_card "psal" "Ravenous Rats" "Swarm of Rats" "[PSAL:A2]"
bin/resolve_card "psal" "Ravenous Rats" "Swarm of Rats" "[PSAL:A27]"
bin/resolve_card "psal" "Ravenous Rats" "Skullsnatcher" "[PSAL:A4]"
bin/resolve_card "psal" "Ravenous Rats" "Skullsnatcher" "[PSAL:A42]"
bin/resolve_card "psal" "Ravenous Rats" "Skullsnatcher" "[PSAL:A43]"
bin/resolve_card "psal" "Ravenous Rats" "Skullsnatcher" "[PSAL:E17]"
bin/resolve_card "psal" "Ravenous Rats" "Skullsnatcher" "[PSAL:E18]"
bin/resolve_card "psal" "Ravenous Rats" "Skullsnatcher" "[PSAL:E19]"
bin/resolve_card "psal" "Ravenous Rats" "Chittering Rats" "[PSAL:A19]"
bin/resolve_card "psal" "Ravenous Rats" "Chittering Rats" "[PSAL:A5]"
bin/resolve_card "psal" "Ravenous Rats" "Chittering Rats" "[PSAL:A54]"
bin/resolve_card "psal" "Ravenous Rats" "Dirty Wererat" "[PSAL:A31]"
bin/resolve_card "psal" "Ravenous Rats" "Dirty Wererat" "[PSAL:A7]"
bin/resolve_card "psal" "Ravenous Rats" "Nezumi Cutthroat" "[PSAL:A17]"
bin/resolve_card "psal" "Ravenous Rats" "Nezumi Cutthroat" "[PSAL:A29]"
bin/resolve_card "psal" "Ravenous Rats" "Nezumi Graverobber" "[PSAL:A38a]"
bin/resolve_card "psal" "Ravenous Rats" "Nezumi Graverobber" "[PSAL:A39a]"
bin/resolve_card "psal" "Ravenous Rats" "Carrion Rats" "[PSAL:A40]"
bin/resolve_card "psal" "Ravenous Rats" "Carrion Rats" "[PSAL:A41]"
bin/resolve_card "psal" "Ravenous Rats" "Carrion Rats" "[PSAL:A53]"
bin/resolve_card "psal" "Ravenous Rats" "Crippling Fatigue" "[PSAL:A30]"
bin/resolve_card "psal" "Ravenous Rats" "Crippling Fatigue" "[PSAL:A6]"
bin/resolve_card "psal" "Ravenous Rats" "Sever Soul" "[PSAL:A15]"
bin/resolve_card "psal" "Ravenous Rats" "Sever Soul" "[PSAL:A16]"
bin/resolve_card "psal" "Ravenous Rats" "Rats' Feast" "[PSAL:A44]"
bin/resolve_card "psal" "Ravenous Rats" "Rats' Feast" "[PSAL:A55]"
bin/resolve_card "psal" "Slivers" "Blade Sliver" "[PSAL:D2]"
bin/resolve_card "psal" "Slivers" "Blade Sliver" "[PSAL:D3]"
bin/resolve_card "psal" "Slivers" "Blade Sliver" "[PSAL:D38]"
bin/resolve_card "psal" "Slivers" "Blade Sliver" "[PSAL:D52]"
bin/resolve_card "psal" "Slivers" "Crypt Sliver" "[PSAL:D29]"
bin/resolve_card "psal" "Slivers" "Crypt Sliver" "[PSAL:D30]"
bin/resolve_card "psal" "Slivers" "Crypt Sliver" "[PSAL:D50]"
bin/resolve_card "psal" "Slivers" "Hunter Sliver" "[PSAL:D53]"
bin/resolve_card "psal" "Slivers" "Hunter Sliver" "[PSAL:D7]"
bin/resolve_card "psal" "Slivers" "Hunter Sliver" "[PSAL:D8]"
bin/resolve_card "psal" "Slivers" "Quick Sliver" "[PSAL:D16]"
bin/resolve_card "psal" "Slivers" "Quick Sliver" "[PSAL:D17]"
bin/resolve_card "psal" "Slivers" "Quick Sliver" "[PSAL:D42]"
bin/resolve_card "psal" "Slivers" "Root Sliver" "[PSAL:D14]"
bin/resolve_card "psal" "Slivers" "Root Sliver" "[PSAL:D15]"
bin/resolve_card "psal" "Slivers" "Spectral Sliver" "[PSAL:D27]"
bin/resolve_card "psal" "Slivers" "Spectral Sliver" "[PSAL:D28]"
bin/resolve_card "psal" "Slivers" "Darigaaz's Charm" "[PSAL:D39]"
bin/resolve_card "psal" "Slivers" "Darigaaz's Charm" "[PSAL:D51]"
bin/resolve_card "psal" "Slivers" "Dark Banishing" "[PSAL:D31]"
bin/resolve_card "psal" "Slivers" "Dark Banishing" "[PSAL:D32]"
bin/resolve_card "psal" "Slivers" "Dark Banishing" "[PSAL:F30]"
bin/resolve_card "psal" "Slivers" "Dark Banishing" "[PSAL:F41]"
bin/resolve_card "psal" "Slivers" "Dark Banishing" "[PSAL:F53]"
bin/resolve_card "psal" "Slivers" "Aphetto Dredging" "[PSAL:D40]"
bin/resolve_card "psal" "Slivers" "Aphetto Dredging" "[PSAL:D41]"
bin/resolve_card "psal" "Slivers" "Crown of Vigor" "[PSAL:B54]"
bin/resolve_card "psal" "Slivers" "Crown of Vigor" "[PSAL:D6]"
bin/resolve_card "psal" "Slivers" "Terrarion" "[PSAL:D19]"
bin/resolve_card "psal" "Slivers" "Terrarion" "[PSAL:D20]"
bin/resolve_card "psal" "Slivers" "Wayfarer's Bauble" "[PSAL:D43]"
bin/resolve_card "psal" "Slivers" "Wayfarer's Bauble" "[PSAL:D44]"
bin/resolve_card "psal" "Spirits" "Blademane Baku" "[PSAL:C30]"
bin/resolve_card "psal" "Spirits" "Blademane Baku" "[PSAL:C4]"
bin/resolve_card "psal" "Spirits" "Blademane Baku" "[PSAL:C53]"
bin/resolve_card "psal" "Spirits" "Frostling" "[PSAL:C16]"
bin/resolve_card "psal" "Spirits" "Frostling" "[PSAL:C6]"
bin/resolve_card "psal" "Spirits" "Kami of the Palace Fields" "[PSAL:C27]"
bin/resolve_card "psal" "Spirits" "Kami of the Palace Fields" "[PSAL:C50]"
bin/resolve_card "psal" "Spirits" "Pain Kami" "[PSAL:C28]"
bin/resolve_card "psal" "Spirits" "Pain Kami" "[PSAL:C29]"
bin/resolve_card "psal" "Spirits" "Phantom Flock" "[PSAL:C3]"
bin/resolve_card "psal" "Spirits" "Phantom Flock" "[PSAL:C39]"
bin/resolve_card "psal" "Spirits" "Phantom Nomad" "[PSAL:C17]"
bin/resolve_card "psal" "Spirits" "Phantom Nomad" "[PSAL:C7]"
bin/resolve_card "psal" "Spirits" "Sandsower" "[PSAL:C51]"
bin/resolve_card "psal" "Spirits" "Sandsower" "[PSAL:J26]"
bin/resolve_card "psal" "Spirits" "Shinen of Fury's Fire" "[PSAL:C42]"
bin/resolve_card "psal" "Spirits" "Shinen of Fury's Fire" "[PSAL:C54]"
bin/resolve_card "psal" "Spirits" "Shinen of Fury's Fire" "[PSAL:C55]"
bin/resolve_card "psal" "Spirits" "Soul of Magma" "[PSAL:C18]"
bin/resolve_card "psal" "Spirits" "Soul of Magma" "[PSAL:C19]"
bin/resolve_card "psal" "Spirits" "Waxmane Baku" "[PSAL:C31]"
bin/resolve_card "psal" "Spirits" "Waxmane Baku" "[PSAL:C32]"
bin/resolve_card "psal" "Spirits" "Volcanic Hammer" "[PSAL:C43]"
bin/resolve_card "psal" "Spirits" "Volcanic Hammer" "[PSAL:K17]"
bin/resolve_card "psal" "Spirits" "Volcanic Hammer" "[PSAL:K31]"
bin/resolve_card "psal" "Spirits" "Spirit Link" "[PSAL:C40]"
bin/resolve_card "psal" "Spirits" "Spirit Link" "[PSAL:G3]"
bin/resolve_card "psal" "Thallids" "Sandsower" "[PSAL:C51]"
bin/resolve_card "psal" "Thallids" "Sandsower" "[PSAL:J26]"
bin/resolve_card "psal" "Thallids" "Savage Thallid" "[PSAL:J4]"
bin/resolve_card "psal" "Thallids" "Savage Thallid" "[PSAL:J5]"
bin/resolve_card "psal" "Thallids" "Selesnya Evangel" "[PSAL:J54]"
bin/resolve_card "psal" "Thallids" "Selesnya Evangel" "[PSAL:J55]"
bin/resolve_card "psal" "Thallids" "Selesnya Guildmage" "[PSAL:B51]"
bin/resolve_card "psal" "Thallids" "Selesnya Guildmage" "[PSAL:J51]"
bin/resolve_card "psal" "Thallids" "Soul Warden" "[PSAL:J14]"
bin/resolve_card "psal" "Thallids" "Soul Warden" "[PSAL:J27]"
bin/resolve_card "psal" "Thallids" "Thallid Germinator" "[PSAL:J19]"
bin/resolve_card "psal" "Thallids" "Thallid Germinator" "[PSAL:J31]"
bin/resolve_card "psal" "Thallids" "Thallid Germinator" "[PSAL:J43]"
bin/resolve_card "psal" "Thallids" "Thallid Shell-Dweller" "[PSAL:J6]"
bin/resolve_card "psal" "Thallids" "Thallid Shell-Dweller" "[PSAL:J7]"
bin/resolve_card "psal" "Thallids" "Sprout" "[PSAL:J30]"
bin/resolve_card "psal" "Thallids" "Sprout" "[PSAL:J41]"
bin/resolve_card "psal" "Thallids" "Strength in Numbers" "[PSAL:J42]"
bin/resolve_card "psal" "Thallids" "Strength in Numbers" "[PSAL:J52]"
bin/resolve_card "psal" "Thallids" "Strength in Numbers" "[PSAL:J53]"
bin/resolve_card "psal" "Thallids" "Fertile Imagination" "[PSAL:J2]"
bin/resolve_card "psal" "Thallids" "Fertile Imagination" "[PSAL:J38]"
bin/resolve_card "psal" "Thallids" "Supply" "[PSAL:J16a]"
bin/resolve_card "psal" "Thallids" "Supply" "[PSAL:J28a]"
bin/resolve_card "psal" "Wizards" "Aven Windreader" "[PSAL:H52]"
bin/resolve_card "psal" "Wizards" "Aven Windreader" "[PSAL:H53]"
bin/resolve_card "psal" "Wizards" "Belltower Sphinx" "[PSAL:H14]"
bin/resolve_card "psal" "Wizards" "Belltower Sphinx" "[PSAL:H26]"
bin/resolve_card "psal" "Wizards" "Martyr of Frost" "[PSAL:H17]"
bin/resolve_card "psal" "Wizards" "Martyr of Frost" "[PSAL:H5]"
bin/resolve_card "psal" "Wizards" "Puppeteer" "[PSAL:H2]"
bin/resolve_card "psal" "Wizards" "Puppeteer" "[PSAL:H39]"
bin/resolve_card "psal" "Wizards" "Soratami Mindsweeper" "[PSAL:H28]"
bin/resolve_card "psal" "Wizards" "Soratami Mindsweeper" "[PSAL:H3]"
bin/resolve_card "psal" "Wizards" "Soratami Mindsweeper" "[PSAL:H50]"
bin/resolve_card "psal" "Wizards" "Soratami Rainshaper" "[PSAL:H30]"
bin/resolve_card "psal" "Wizards" "Soratami Rainshaper" "[PSAL:H43]"
bin/resolve_card "psal" "Wizards" "Vedalken Dismisser" "[PSAL:H54]"
bin/resolve_card "psal" "Wizards" "Vedalken Dismisser" "[PSAL:H55]"
bin/resolve_card "psal" "Wizards" "Vedalken Entrancer" "[PSAL:H18]"
bin/resolve_card "psal" "Wizards" "Vedalken Entrancer" "[PSAL:H31]"
bin/resolve_card "psal" "Wizards" "Vedalken Entrancer" "[PSAL:H44]"
bin/resolve_card "psal" "Wizards" "Vedalken Entrancer" "[PSAL:H7]"
bin/resolve_card "psal" "Wizards" "Boomerang" "[PSAL:H16]"
bin/resolve_card "psal" "Wizards" "Boomerang" "[PSAL:H29]"
bin/resolve_card "psal" "Wizards" "Vacuumelt" "[PSAL:H4]"
bin/resolve_card "psal" "Wizards" "Vacuumelt" "[PSAL:H40]"
bin/resolve_card "psal" "Wizards" "Dehydration" "[PSAL:H41]"
bin/resolve_card "psal" "Wizards" "Dehydration" "[PSAL:H42]"
bin/resolve_card "psal" "Zombies" "Blind Creeper" "[PSAL:F29]"
bin/resolve_card "psal" "Zombies" "Blind Creeper" "[PSAL:F4]"
bin/resolve_card "psal" "Zombies" "Festering Goblin" "[PSAL:F17]"
bin/resolve_card "psal" "Zombies" "Festering Goblin" "[PSAL:F5]"
bin/resolve_card "psal" "Zombies" "Festering Goblin" "[PSAL:F6]"
bin/resolve_card "psal" "Zombies" "Golgari Guildmage" "[PSAL:B50]"
bin/resolve_card "psal" "Zombies" "Golgari Guildmage" "[PSAL:F39]"
bin/resolve_card "psal" "Zombies" "Gravedigger" "[PSAL:F43]"
bin/resolve_card "psal" "Zombies" "Gravedigger" "[PSAL:F55]"
bin/resolve_card "psal" "Zombies" "Gravedigger" "[PSAL:F7]"
bin/resolve_card "psal" "Zombies" "Nantuko Husk" "[PSAL:F15]"
bin/resolve_card "psal" "Zombies" "Nantuko Husk" "[PSAL:F27]"
bin/resolve_card "psal" "Zombies" "Nantuko Husk" "[PSAL:F3]"
bin/resolve_card "psal" "Zombies" "Plagued Rusalka" "[PSAL:F28]"
bin/resolve_card "psal" "Zombies" "Plagued Rusalka" "[PSAL:F40]"
bin/resolve_card "psal" "Zombies" "Spineless Thug" "[PSAL:F18]"
bin/resolve_card "psal" "Zombies" "Spineless Thug" "[PSAL:F19]"
bin/resolve_card "psal" "Zombies" "Spineless Thug" "[PSAL:F31]"
bin/resolve_card "psal" "Zombies" "Woebearer" "[PSAL:F16]"
bin/resolve_card "psal" "Zombies" "Woebearer" "[PSAL:F51]"
bin/resolve_card "psal" "Zombies" "Dark Banishing" "[PSAL:D31]"
bin/resolve_card "psal" "Zombies" "Dark Banishing" "[PSAL:D32]"
bin/resolve_card "psal" "Zombies" "Dark Banishing" "[PSAL:F30]"
bin/resolve_card "psal" "Zombies" "Dark Banishing" "[PSAL:F41]"
bin/resolve_card "psal" "Zombies" "Dark Banishing" "[PSAL:F53]"
bin/resolve_card "psal" "Zombies" "Death Denied" "[PSAL:F42]"
bin/resolve_card "psal" "Zombies" "Death Denied" "[PSAL:F54]"
```

**Pull request merged**
